apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  labels:
    app: bazel-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bazel-java
  template:
    metadata:
      labels:
        app: bazel-java
    spec:
      containers:
      - name: bazel-java
        image: 850692499868.dkr.ecr.ap-southeast-1.amazonaws.com/dev-evyd-containers:7dbbbe7d98f90926f7a89bd962f3519f7be3d09a
        ports:
        - containerPort: 80
