apiVersion: batch/v1
kind: Job
metadata:
  name: bazel-java
spec:
  template:
    spec:
      containers:
      - name: bazel-java
        image: 850692499868.dkr.ecr.ap-southeast-1.amazonaws.com/dev-evyd-containers
      restartPolicy: Never
  backoffLimit: 3