apiVersion: batch/v1
kind: Job
metadata:
  name: bazel-java
spec:
  template:
    spec:
      containers:
      - name: bazel-java
        image: evydinternalacr.azurecr.io/bazel-java
      restartPolicy: Never
  backoffLimit: 3