apiVersion: batch/v1
kind: Job
metadata:
  name: bazel-java
spec:
  template:
    spec:
      containers:
      - name: dev-evyd-containers
        image: 850692499868.dkr.ecr.ap-southeast-1.amazonaws.com/dev-evyd-containers:latest
      restartPolicy: Never
      imagePullSecrets:
      - name: regcred
  backoffLimit: 3